version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: pos_postgres
    environment:
      POSTGRES_DB: pos_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pos_network

  # Product Service
  product-service:
    build: 
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product_service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: pos_system
      PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - pos_network

  # Transaction Service
  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    container_name: transaction_service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: pos_system
      PRODUCT_SERVICE_URL: http://product-service:8081
      PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - product-service
    networks:
      - pos_network

  # API Gateway (Nginx)
  api-gateway:
    image: nginx:alpine
    container_name: pos_gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - product-service
      - transaction-service
    networks:
      - pos_network

volumes:
  postgres_data:

networks:
  pos_network:
    driver: bridge